import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/Banner";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerBtnClick = (e) => {
    console.log("clicked button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroImage}>
            <Image
              src="/static/hero.png"
              width={1920}
              height={875}
              alt="Hero Image"
            />
          </div>
          <Banner
            buttonText="View stores nearby"
            buttonHandler={handleOnBannerBtnClick}
          />
        </div>
      </main>
    </div>
  );
}
